"""add_indexes

Revision ID: 76db38cc50ab
Revises: b97fee69db6c
Create Date: 2026-03-06 18:43:38.106574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76db38cc50ab'
down_revision: Union[str, Sequence[str], None] = 'b97fee69db6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_labels_post_id'), 'labels', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_locations_post_id'), 'post_locations', ['post_id'], unique=False)
    op.create_index('ix_post_locations_type_id', 'post_locations', ['location_type', 'location_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_solutions_umbrella_issue_id'), 'solutions', ['umbrella_issue_id'], unique=False)
    op.create_index(op.f('ix_solutions_upvote_count'), 'solutions', ['upvote_count'], unique=False)
    op.create_index(op.f('ix_solutions_user_id'), 'solutions', ['user_id'], unique=False)
    op.create_index('ix_umbrella_issues_type_id', 'umbrella_issues', ['location_type', 'location_id'], unique=False)
    op.create_index(op.f('ix_votes_post_id'), 'votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_post_id'), table_name='votes')
    op.drop_index('ix_umbrella_issues_type_id', table_name='umbrella_issues')
    op.drop_index(op.f('ix_solutions_user_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_upvote_count'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_umbrella_issue_id'), table_name='solutions')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index('ix_post_locations_type_id', table_name='post_locations')
    op.drop_index(op.f('ix_post_locations_post_id'), table_name='post_locations')
    op.drop_index(op.f('ix_labels_post_id'), table_name='labels')
    # ### end Alembic commands ###
