"""add governance levels to solutions and location to users

Revision ID: 9ad861d88d23
Revises: 76db38cc50ab
Create Date: 2026-03-07 12:09:52.531804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ad861d88d23'
down_revision: Union[str, Sequence[str], None] = '76db38cc50ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('governance_levels', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('solutions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('users', sa.Column('county_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.create_index(op.f('ix_users_county_id'), 'users', ['county_id'], unique=False)
    op.create_foreign_key(None, 'users', 'counties', ['county_id'], ['id'])
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_county_id'), table_name='users')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_column('users', 'city_id')
    op.drop_column('users', 'county_id')
    op.alter_column('solutions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('solutions', 'governance_levels')
    # ### end Alembic commands ###
