"""allow multiple solutions per post

Revision ID: b9f42abdbef8
Revises: 9ad861d88d23
Create Date: 2026-03-07 12:16:44.639657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f42abdbef8'
down_revision: Union[str, Sequence[str], None] = '9ad861d88d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('solutions_post_id_key'), 'solutions', type_='unique')
    op.create_index(op.f('ix_solutions_post_id'), 'solutions', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_post_id'), table_name='solutions')
    op.create_unique_constraint(op.f('solutions_post_id_key'), 'solutions', ['post_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
